### ISSUE TITLE
Zero-width space

### ISSUE THREAD

**Issue by photopea** [bbc/unicode-bidirectional#23] opened 2017-07-19 20:30 UTC
Hi, I try to order zero-width space character (200b)

    var cdp = [8203, 8203, 8203, 8203, 8203, 8203, 8203, 10];
    var lvls = UnicodeBidirectional.resolve(cdp);  // lvls = ["x", "x", "x", "x", "x", "x", "x", 0]
    var perm = UnicodeBidirectional.reorderPermutation(lvls) // perm = [7]

Is this an expected behavior?  I was quite surprised by the fact, that I started with 8 characters, but received the permutation of 1 character (which is not even a permutation) at the end, so my program crashed.

**Comment by jameslawson** [comment] 2017-07-24 08:33
This is expected behaviour and there are [unit tests](https://github.com/bbc/unicode-bidirectional/blob/f00b55719c92ba6cbe5bc4057bbde3f8e8b7dd52/test/unit/resolve/reorderLevels.spec.js#L85) covering this behaviour. But I completely agree that this behaviour is not very intuitive -- `[7]` is definitely not a valid permutation of 8 characters! Thank for you bringing this to my attention.

I've fixed this behaviour so now `reorderPermutation` will *always* give a permutation (not ignore levels of x). Regardless of whether there are any 'x's in the levels array, you'll always have the expected number of items in the permutation array. This fix will soon be released in [v2.0.0](https://github.com/bbc/unicode-bidirectional/releases), (see link to download newer version of unicode.bidirectional.js). I've also improved the README so that is explains what these x's mean. There's also an explanation below for why this behaviour exists in v1.x.x.

Thanks again, @photopea ! 

----

**Why are there x's in the levels array?**
This is expected behaviour. The reason is because the Unicode Bidirectional algorithm (by rule [X9](http://unicode.org/reports/tr9/#X9).) will not assign a level to certain invisible characters / control characters. They are basically completely ignored by the algorithm. They are invisible and so have no impact on the visual RTL/LTR ordering of characters. Most of the invisible characters that fall into this category are in this [list](https://www.compart.com/en/unicode/bidiclass/BN). The zero-width space character (U+200) is in this list which is why it has a level of x (it is ignored). 

**In v1.x.x, why was the permutation returned by `reorderPermutation` not actually a permutation?**
If any characters have a level of `x`, then *reorderPermutation* ignores these characters when forming the permutation array. The result is a *partial* permutation (a partial function). The reason why v1.0.0 uses this behaviour is because it follows how the Unicode Conformance tests formats permutations involving x's, which at the time, was the easiest thing to do to get the conformance tests to pass. From the [conformance test's definition](http://www.unicode.org/Public/UCD/latest/ucd/BidiTest.txt) of `<ordering>` (a permutation):

> `<ordering>` = An ordered space-delimited list of numbers indicating the resulting visual ordering from left to right. The numbers are zero-based, and are indexes into the input string. **Items with a level of x are skipped**

As @photopea has pointed out, this behaviour is not intuitive and a bit confusing in practice. So in v2.0.0 I've made `reorderPermutation` capable of handling *both* cases. So now, it can create permutations that include levels with 'x' (more intuitive), or it can ignore levels with 'x'. This is controlled by the second parameter, `IGNORE_VISIBLE`, for the function: `reorderPermutation(levels, IGNORE_INVISIBLE = false)`. In v2.0.0, by default, reorderPermutation includes levels with 'x' (`IGNORE_VISIBLE` is *false* by default).

**Comment by jameslawson** [comment] 2017-07-24 08:47
With v2.0.0, the behaviour is now:
```
var cdp = [8203, 8203, 8203, 8203, 8203, 8203, 8203, 10];
var lvls = UnicodeBidirectional.resolve(cdp);  // lvls = ["x", "x", "x", "x", "x", "x", "x", 0]
var perm = UnicodeBidirectional.reorderPermutation(lvls) // perm = [0, 1, 2, 3, 4, 5, 6, 7]
```

**Comment by photopea** [comment] 2017-07-24 14:31
Hi James, you are amazing, thank you!  By the way, I think that the .min.js version is still an old one.

**Comment by jameslawson** [comment] 2017-07-24 15:10
No problem! 

And sorry, you're right. I've created a new release v2.0.1. This should have the correct .min.js file.

**Closed by jameslawson** 2017-07-24 15:10 UTC
